# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  # Cypress E2E 테스트 작업
  cypress-run:
    docker:
      - image: cypress/base:16 # Cypress에서 지원하는 Node.js와 브라우저가 포함된 이미지 사용
    steps:
      - checkout # 소스 코드 체크아웃
      - run:
          name: Install dependencies
          command: npm install # 프로젝트의 종속성 설치
      - run:
          name: Start server
          command: npm run start & # 애플리케이션 서버 시작 (백그라운드에서 실행)
      - cypress/run:
          start-command: "npm run start" # Cypress 실행

  # Simple hello job
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Workflows 섹션
workflows:
  # 기존의 say-hello-workflow와 별개로, build 워크플로우를 정의합니다.
  build:
    jobs:
      - cypress-run

  # 기존의 say-hello-workflow
  say-hello-workflow:
    jobs:
      - say-hello
